### ISSUE TITLE
Add table view for job

### ISSUE THREAD

**Issue by crertel** [jeffrey-hokanson/FlowXL#2]
We'd like to be able to see a nice representation of the files and columns referenced in a job.

This issue would involve:
- creating a static assets folder for CSS and JS supporting files
- creating a jinja templates folder
  - creating a default layout (which includes the normal navbar and static resources)
  - creating a table page for displaying the details about a job
- writing a frontend script to load and render the table for a job

**Comment by jeffrey-hokanson** [comment]
Created branch `issue-2`.
